### ISSUE TITLE
UI Record Creation Fails When Field in Header

### ISSUE THREAD

**Issue by mike9182** [DynamicHands/Crm.Specflow#73]
The following step fails with the error below. This appears to be because in my target environment, the "Job Title" field is in the form header.

**Step**
```
Given a contact named TestContact with the following values
    | Property   | Value |
    | First Name | John  |
    | Last Name  | Smith |
    | Job Title  | CLO   |
```

**Exception** 
```
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=javascript error: Cannot read property 'getName' of null
  (Session info: chrome=80.0.3987.163)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ExecuteScript(IWebDriver driver, String script, Object[] args)
   at Vermaat.Crm.Specflow.EasyRepro.FormField.GetTabName() in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\EasyRepro\FormField.cs:line 98
   at Vermaat.Crm.Specflow.EasyRepro.FormData.FillForm(CrmTestingContext crmContext, Table formData) in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\EasyRepro\FormData.cs:line 95
   at Vermaat.Crm.Specflow.Commands.CreateRecordCommand.ExecuteBrowser() in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\Commands\CreateRecordCommand.cs:line 36
   at Vermaat.Crm.Specflow.Commands.BrowserCommandFunc`1.Execute(CommandAction commandAction) in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\Commands\BrowserCommand.cs:line 29
   at Vermaat.Crm.Specflow.CommandProcessor.Execute[TResult](ICommandFunc`1 command, CommandAction commandAction) in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\CommandProcessor.cs:line 55
   at Vermaat.Crm.Specflow.CommandProcessor.Execute[TResult](ICommandFunc`1 command) in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\CommandProcessor.cs:line 47
   at Vermaat.Crm.Specflow.Steps.GeneralSteps.GivenEntityWithValues(String entityName, String alias, Table criteria) in C:\Projects\open-source\Crm.Specflow\Vermaat.Crm.Specflow\Steps\GeneralSteps.cs:line 40
```

**Comment by mVermaat** [comment]
I'll look into this. Looks like a bug
